language: node_js

node_js:
- "node"

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - DATABASE_URL=null
  - DATABASE_MIGRATIONS_DIR=null
  - DATABASE_MIGRATIONS_TABLE=null
  - PGSSLMODE=require
  - SECRET_PATH=null
  - ORIGIN=null
  - CLIENTS=null
  - IDENTITY_SERVICE_HOST=null  
  - GEMFURY_USER=neoncity
  - LOGGLY_TOKEN=null
  - LOGGLY_SUBDOMAIN=null
  # GEMFURY_API_KEY=???
  - secure: "bCwbM/x4M4mE6Gva/gQvd8wkQEwMAYU2s/kKSIRDzIM/hej5/PoYXnL6G67zh1At7CdpsYOF/yD8JHHHp6mgzFCltnhmFLbpSc3KPjk47dVb06utsLT2+wTTmiiT9rfrzkK5IwRCSuuqknPK2VTBnht4lNT6helhEtKTtkLQTB60KqeJ2c5rk/Qsbw5Nsc4mpsA9PYVZZ9jg3z9OdRtRqty0jl/HSlknt3+ITKgf4ElDoqxo7PA1QfjWIaCTsy9XeoAfnO/rz1pdGbLXUuSGbBfNZSmY7WJI3UX3ytaEcvMqPsNKdN5QR4yu7SLwkN/V0w2iS9J/ZhXvBZJ+87I2aD/syBDR8JlEKsTb4jWTbuO4Lcr2Nwy6ZioBBGgfFyT5A3N51HxgRBc4iOmoMx9qWYbgIqF+CE0Nra7vn+N64DypvaObo5cDf2Iol9u3m/RpkporutanKN0HoZnIL0bkJzP1N/5GYfYEHFacd7z4ZLRA3zg50JIve3GYP3PhjS+S2rEzViczrNP0DUk8ZKmgHbcC5ix1qmThcRwIem897FUTDtM/Hl2z0lbqrN5W+r/Sk22Twtx54T/f6lergwilKu9ESm/arqRxXfTOylYV2xsJW9VCkCDN0vZrGs+z+hSWxvlcfzNj9bnb5xmMv93f4WVdOfvRRR6uVdAymweTTO0="

install:
- npm install --registry=https://npm-proxy.fury.io/${GEMFURY_API_KEY}/${GEMFURY_USER}/ --progress=false

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/togemfury --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
- provider: heroku
  skip_cleanup: true
  app: core-staging-neoncity
  api_key:
    secure: "RzgAzJo9hBa6Qsb8cdspRIeFExeKgWd0dj9cbKP7F30qlmCa12rZkohwXsQurDVE2vWdeqYaEsCBdrSEXRKexjZuC1qTZyN27tsAMyZjS+iMOpQ0Qh/uF0GraPlTuRGJIOoOD8NfbjDogEECcSvlR2D73wzCzS0jCbAsNUax3H1rClrDIzch1JA8uy8e28u1deoyi5Cown4eV5cdZQ4Mkqy1K/+phB86WMS/JhukjRGBfpsdDELmnyp8wJ5mIrzsHCSPhCPBOh6aOVqHaXhtOtcZ5JlCRpDpv7lEjyL5ypji+GCHWupGesH7fmTX4HTdejhEfgXwyfeV8ZsEGwxpgsgWa1ryTuBmXFi15hCdJev6mrNNCV7Fb/i++LG3SM6WAjc8tZuSf9F0aIKcbhJuuLlYb7VWvVxja3NEQrHbygdvslPVpI90Q5msypQfWcShxT1sCEkRmzF4faWNPuNfPuoXlAvtpsAbpKs9DmEgBKDL20cgp861oCqvYRoUqqrsMYsgVlaw6w5g3wfk6duiC3CJ2KUXQGsv9pZ5GW3rYVhei6lpSDzMGD3AxZ9Miz9D8T2LAdqwziU3XSO1AvCm5cnJG5BzCeChD3wjs9yGdvIm3B29OL34mtM6KngR9A/DCZdnLsQeA7weJVfPgQ+HppS+R8BpxE/KoO9I4YJKQXk="
