language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - DATABASE_URL=null
  - DATABASE_MIGRATIONS_DIR=null
  - DATABASE_MIGRATIONS_TABLE=null
  - PGSSLMODE=require
  - SECRET_PATH=null
  - CLIENTS=null
  - GEMFURY_USER=neoncity
  # GEMFURY_API_KEY=???
  - secure: "bCwbM/x4M4mE6Gva/gQvd8wkQEwMAYU2s/kKSIRDzIM/hej5/PoYXnL6G67zh1At7CdpsYOF/yD8JHHHp6mgzFCltnhmFLbpSc3KPjk47dVb06utsLT2+wTTmiiT9rfrzkK5IwRCSuuqknPK2VTBnht4lNT6helhEtKTtkLQTB60KqeJ2c5rk/Qsbw5Nsc4mpsA9PYVZZ9jg3z9OdRtRqty0jl/HSlknt3+ITKgf4ElDoqxo7PA1QfjWIaCTsy9XeoAfnO/rz1pdGbLXUuSGbBfNZSmY7WJI3UX3ytaEcvMqPsNKdN5QR4yu7SLwkN/V0w2iS9J/ZhXvBZJ+87I2aD/syBDR8JlEKsTb4jWTbuO4Lcr2Nwy6ZioBBGgfFyT5A3N51HxgRBc4iOmoMx9qWYbgIqF+CE0Nra7vn+N64DypvaObo5cDf2Iol9u3m/RpkporutanKN0HoZnIL0bkJzP1N/5GYfYEHFacd7z4ZLRA3zg50JIve3GYP3PhjS+S2rEzViczrNP0DUk8ZKmgHbcC5ix1qmThcRwIem897FUTDtM/Hl2z0lbqrN5W+r/Sk22Twtx54T/f6lergwilKu9ESm/arqRxXfTOylYV2xsJW9VCkCDN0vZrGs+z+hSWxvlcfzNj9bnb5xmMv93f4WVdOfvRRR6uVdAymweTTO0="

install:
- npm install --registry=https://npm-proxy.fury.io/${GEMFURY_API_KEY}/${GEMFURY_USER}/ --progress=false

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/togemfury --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
- provider: heroku
  skip_cleanup: true
  app: core-staging-neoncity
  api_key:
    secure: "an30nkAb+eIvcfOIC4aND0eyLFXEwJfK55TM6EEWTINiGnfwKgGti72622huYYjKK2Scn1vQ9H2ErfcmnnSOLfKkJsdeZW3Vd+ABJXYR/+lH4cGFW6HpbuCdhej+o7uiGcr7rLpjp/pBwtHUCicm6rhPwIUIzCkbwiFgagGilLkSUqKTlwI6ExJZHNp+TmzXCOhvKHUuyINxI+R2q3YUlyW5bdlfU5/pkDH4/dBCBIR12H4HBBiZTD9JA6HL1mlDGttIw3LHgmEGQMfbzgAKRx/8VhnX0AbLazgiP0iPFqNhzzReWn49QwW6YMww1WEDmmLC766pkBqzVZFZL82hmZob+FDIHK88jhWhIhQI+XIVJo/47PW9YmpW/4QRL6pHa69+dJ9/X2LMQL+KTs2j2d/72qrI75MBLPSLeJe1Iakq8NGMCyhKOn1X/lECzSgJ2EZ+yuVM5h0e9dhsebPt0C5+SNsdDojVsFi5Au8NY6+f119mA637cHeSOtFQgbyo01M++7/F9NdsKYfHN/2jT5bnHve/HFVazestOLYa9xtL9a6lK2K4YZCb356RQ6JPki7cpxoUNDCSKcCSBXLUS2Oy+gfy3f4GrBciWTYEgsHWn5u3XIz/ZhJSXTGO1OvQp3toLvnNS/uzWeoOzJ64YSWQHB2EXQ3zRDYIaCaQZHs="
